graph TD
    A(( ))

    A --- B(( ))
    A --- C(( ))
    A --- D(( ))
    A --- E(( ))
    A --- F(( ))

    C --- G(( ))
    D --- H(( ))
    D --- J(( ))
    E --- I(( ))
    E --- K(( ))
    E --- L(( ))
    F --- M(( ))
    F --- N(( ))
    F --- O(( ))
    F --- P(( ))

    J --- Q(( ))
    K --- R(( ))
    L --- S(( ))
    L --- T(( ))
    N --- U(( ))
    O --- V(( ))
    O --- W(( ))
    P --- X(( ))
    P --- Y(( ))
    P --- Z(( ))

    T --- a(( ))
    W --- b(( ))
    Y --- c(( ))
    Z --- d(( ))
    Z --- e(( ))

    e --- f(( ))

    classDef zero  fill:LightCoral
    classDef one   fill:SpringGreen
    classDef two   fill:SkyBlue
    classDef three fill:MediumPurple
    classDef four  fill:#b666d2

    class A zero
    class B,C,D,E,F one
    class G,H,J,I,K,L,M,N,O,P two
    class Q,R,S,T,U,V,W,X,Y,Z three
    class a,b,c,d,e four
