graph TD
    subgraph k = 3
    F((2))
    F --- G((8))
    F --- H((9))
    F --- I((21))
    H --- J((1))
    I --- K((15))
    I --- L((24))
    L --- M((19))
    end
    subgraph k = 2
    B((12))
    B --- C((7))
    B --- D((4))
    D --- E((5))
    end
    subgraph k = 0
    A((3))
    end
