graph TD
    subgraph k = 2
    A((3))
    A --- N((4))
    A --- O((7))
    O --- P((30))
    end
    classDef first fill:SpringGreen
    class A,B,C,D,E,F,G,H,I,J,K,L,M first
    classDef second fill:LightCoral
    class N,O,P second
