graph TD
    subgraph k = 3
    H(( ))
    H --- I(( ))
    H --- J(( ))
    H --- K(( ))
    J --- L(( ))
    K --- M(( ))
    K --- N(( ))
    N --- O(( ))
    end

    subgraph k = 2
    D(( ))
    D --- E(( ))
    D --- F(( ))
    F --- G(( ))
    end

    subgraph k = 1
    B(( ))
    B --- C(( ))
    end

    subgraph k = 0
    A(( ))
    end
