graph TD
    subgraph 2
    xr((x))
    xr --- ar{α}
    xr --- yr((y))
    yr --- br{β}
    yr --- gr{γ}
    end

    subgraph 1
    yl((y))
    yl --- xl((x))
    yl --- gl{γ}
    xl --- al{α}
    xl --- bl{β}
    end
