graph TD
    subgraph k = 3
    A((3))
    A --- N((4))
    A --- O((7))
    O --- P((30))
    A --- B((4))
    B --- C((7))
    B --- D((5))
    D --- E((12))
    end
    subgraph k = 2
    I((15))
    I --- K((21))
    I --- L((19))
    L --- M((24))
    end
    subgraph k = 1
    H((2))
    H --- J((9))
    end
    subgraph k = 0
    G((8))
    end
    classDef first fill:SpringGreen
    class A,B,C,D,E,F,G,H,I,J,K,L,M first
    classDef second fill:LightCoral
    class N,O,P second
