name: hugo
on:
  push:
    branches:
      - develop
jobs:
  hugo:
    runs-on: ubuntu-20.04
    env:
      VERSION: '0.88.1'
    steps:
      - name: download
        run: wget "https://github.com/gohugoio/hugo/releases/download/v${VERSION}/hugo_${VERSION}_Linux-64bit.tar.gz"
      - name: install
        run: tar xvf hugo_${VERSION}_Linux-64bit.tar.gz
      - name: build
        run: ./hugo_${VERSION}_Linux-64bit/hugo
